# This is a basic workflow that is manually triggered

name: twrpdtgen

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      the_url_of_boot_or_recovery:
        description: 'the url of boot or recovery'
        required: true
        default: 'World'
      image_name:
        description: 'the name of image'
        required: true
        default: 'recovery.img'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Configuring the environment
      run: sudo apt -y install git cpio wget aria2 brotli android-sdk-libsparse-utils android-sdk-ext4-utils python3.9 pip
           
    - name: install twrpdtgen
      run: pip install twrpdtgen

    - name: download the image
      run: wget ${{ github.event.inputs.the_url_of_boot_or_recovery }}

    - name: install twrpdtgen
      run: python3.9 -m.twrpdtgen boot.img
